version: '3.8'

services:
  frontend:
    build:
      context: ./wishlist
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Tools3Project
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - app-network

  mongo:

    image: mongo:latest
    restart: always
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: